[package]
name = "gh"
version = "0.0.2-SNAPSHOT"
authors = ["penland365 <Jeffrey.N.Davis@gmail.com>"]

[dependencies]
clap = "2.24.1"
curl = "0.4.6"
rustc-serialize = "^0.3"
serde = "1.0.5"
serde_derive = "^1.0"
serde_json = "^1.0"
version = "2.0.1"

[dev-dependencies]
quickcheck = "0.4.1"
